# Generated by Django 5.2.7 on 2026-05-23 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Permission Name')),
                ('codename', models.CharField(max_length=100, unique=True, verbose_name='Codename')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Permission',
                'verbose_name_plural': 'Permissions',
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='permissiongroup',
            options={'verbose_name': 'Permission Group', 'verbose_name_plural': 'Permission Groups'},
        ),
        migrations.AddField(
            model_name='permissiongroup',
            name='permissions',
            field=models.ManyToManyField(blank=True, to='accounts.permission'),
        ),
        migrations.AddField(
            model_name='role',
            name='permissions',
            field=models.ManyToManyField(blank=True, to='accounts.permission'),
        ),
    ]
